name: PR

on: [pull_request]

jobs:
  test:
    name: Jira
    runs-on: ubuntu-latest
    steps:
    - uses: openstax/jira-linked-action@v0.1.4
      with:
        jira-project: DISCO
        jira-email: ${{ secrets.JiraEmail }}
        jira-token: ${{ secrets.JiraToken }}

