name: PR

on: [pull_request]

jobs:
  test:
    name: Jira
    runs-on: ubuntu-latest
    steps:
    - uses: openstax/jira-linked-action@v0.1.11
      with:
        jira_site: openstax
        jira_project: DISCO
        jira_email: ${{ secrets.JiraEmail }}
        jira_token: ${{ secrets.JiraToken }}

